Repository Dia218/webty-backend-spring, pull requests merged in 2025-01, with the labels that each got.

#8 Feat : 닉네임 자동등록 및 닉네임 수정 구현 (#6)
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/user/controller/UserController.java
  src/main/java/org/team14/webty/user/dto/NicknameRequest.java
  src/main/java/org/team14/webty/user/dto/NicknameResponse.java
  src/main/java/org/team14/webty/user/entity/ProviderType.java
  src/main/java/org/team14/webty/user/entity/SocialProvider.java
  src/main/java/org/team14/webty/user/entity/WebtyUser.java
  src/main/java/org/team14/webty/user/repository/SocialProviderRepository.java
  src/main/java/org/team14/webty/user/repository/UserRepository.java
  src/main/java/org/team14/webty/user/service/UserService.java
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/docs/application.md
Labels: new-feature, multiple-file-changes

#11 Feat : 프로필사진 자동등록 및 프로필 이미지 변경 구현
  .gitignore
  src/main/java/org/team14/webty/common/util/FileStorageUtil.java
  src/main/java/org/team14/webty/user/controller/UserController.java
  src/main/java/org/team14/webty/user/dto/ImageResponse.java
  src/main/java/org/team14/webty/user/service/UserService.java
  uploads/iconmonstr-user-circle-thin-240.png
Labels: new-feature

#13 feat: Implement CookieManager
  src/main/java/org/team14/webty/common/cookies/CookieManager.java
  src/main/java/org/team14/webty/common/enums/TokenType.java
  src/main/java/org/team14/webty/security/policy/ExpirationPolicy.java
  src/main/java/org/team14/webty/security/token/JwtManager.java
  src/main/java/org/team14/webty/security/token/RefreshToken.java
Labels: new-feature, shared-feature

#19 refactor: FileStorageUtil & 경로명 상수화, 파일 경로 변경
  .gitignore
  src/main/java/org/team14/webty/common/util/FileStorageUtil.java
  src/main/java/org/team14/webty/user/service/UserService.java
  src/main/resources/image/iconmonstr-user-circle-thin-240.png
Labels: refactor

#17 refactor: Rename OAuthLoginSuccessHandler, OAuth2UserInfo
  src/main/java/org/team14/webty/security/oauth2/LoginSuccessHandler.java
  src/main/java/org/team14/webty/security/oauth2/ProviderUserInfo.java
Labels: typo-fix

#21 feat: Implement CustomAuthenticationFilter
  src/main/java/org/team14/webty/common/cookies/CookieManager.java
  src/main/java/org/team14/webty/security/token/CustomAuthenticationFilter.java
  src/main/java/org/team14/webty/security/token/JwtManager.java
Labels: new-feature

#25 feat: getUserData 구현 및 기존 함수 오류 수정
  src/main/java/org/team14/webty/user/controller/UserController.java
  src/main/java/org/team14/webty/user/dto/UserDataResponse.java
  src/main/java/org/team14/webty/user/service/UserService.java
Labels: bugfix, new-feature

#27 feat: JwtManager 구현
  src/main/java/org/team14/webty/security/token/JwtManager.java
Labels: new-feature

#44 feat: Implement Webtoon Save
  src/main/java/org/team14/webty/common/config/RestTemplateConfig.java
  src/main/java/org/team14/webty/webtoon/api/WebtoonApiResponse.java
  src/main/java/org/team14/webty/webtoon/api/WebtoonPageApiResponse.java
  src/main/java/org/team14/webty/webtoon/controller/WebtoonController.java
  src/main/java/org/team14/webty/webtoon/entity/Webtoon.java
  src/main/java/org/team14/webty/webtoon/enumerate/Platform.java
  src/main/java/org/team14/webty/webtoon/mapper/WebtoonApiResponseMapper.java
  src/main/java/org/team14/webty/webtoon/repository/FavoriteRepository.java
  src/main/java/org/team14/webty/webtoon/repository/WebtoonRepository.java
  src/main/java/org/team14/webty/webtoon/service/WebtoonService.java
Labels: new-feature

#49 feature: Webtoon 저장 구현 (KAKAO_PAGE, NAVER)
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/security/token/CustomAuthenticationFilter.java
  src/main/java/org/team14/webty/webtoon/controller/WebtoonController.java
  src/main/java/org/team14/webty/webtoon/service/WebtoonService.java
Labels: new-feature
