Repository Dia218/webty-backend-spring, pull requests merged in 2025-02, with the labels that each got.

#30 fix(JwtManager): createRefreshToken & getAuthentication
  src/main/java/org/team14/webty/security/authentication/CustomAuthenticationFilter.java
  src/main/java/org/team14/webty/security/authentication/WebtyUserDetails.java
  src/main/java/org/team14/webty/security/authentication/WebtyUserDetailsService.java
  src/main/java/org/team14/webty/security/token/JwtManager.java
  src/main/java/org/team14/webty/security/token/RefreshToken.java
  src/main/java/org/team14/webty/security/token/RefreshTokenRepository.java
  src/main/java/org/team14/webty/user/service/UserService.java
  src/test/java/org/team14/webty/security/token/JwtManagerTest.java
Labels: tests-passed, execution-ok

#50 feature: 웹툰 데이터베이스 업데이트 구현
  src/main/java/org/team14/webty/common/config/SchedulerConfig.java
  src/main/java/org/team14/webty/webtoon/mapper/WebtoonApiResponseMapper.java
  src/main/java/org/team14/webty/webtoon/service/WebtoonService.java
Labels: new-feature

#47 Feat:관심 웹툰 추가,삭제,확인 구현
  src/main/java/org/team14/webty/webtoon/controller/FavoriteController.java
  src/main/java/org/team14/webty/webtoon/dto/FavoriteDto.java
  src/main/java/org/team14/webty/webtoon/dto/WebtoonResponseDto.java
  src/main/java/org/team14/webty/webtoon/entity/Favorite.java
  src/main/java/org/team14/webty/webtoon/mapper/FavoriteMapper.java
  src/main/java/org/team14/webty/webtoon/mapper/WebtoonApiResponseMapper.java
  src/main/java/org/team14/webty/webtoon/repository/FavoriteRepository.java
  src/main/java/org/team14/webty/webtoon/service/FavoriteService.java
  src/main/resources/application-prod.yml
Labels: bugfix, new-feature

#51 feat: 댓글 및 대댓글 읽기/작성/수정/삭제
  src/main/java/org/team14/webty/common/response/StandardResponse.java
  src/main/java/org/team14/webty/review/controller/ReviewCommentController.java
  src/main/java/org/team14/webty/review/entity/Review.java
  src/main/java/org/team14/webty/review/entity/ReviewComment.java
  src/main/java/org/team14/webty/review/repository/ReviewCommentRepository.java
  src/main/java/org/team14/webty/review/service/ReviewCommentService.java
  src/main/java/org/team14/webty/reviewComment/controller/ReviewCommentController.java
  src/main/java/org/team14/webty/reviewComment/dto/CommentRequest.java
  src/main/java/org/team14/webty/reviewComment/dto/CommentResponse.java
  src/main/java/org/team14/webty/reviewComment/entity/ReviewComment.java
  src/main/java/org/team14/webty/reviewComment/mapper/ReviewCommentMapper.java
  src/main/java/org/team14/webty/reviewComment/repository/ReviewCommentRepository.java
  src/main/java/org/team14/webty/reviewComment/service/ReviewCommentService.java
  src/main/java/org/team14/webty/user/entity/WebtyUser.java
  src/test/java/org/team14/webty/review/controller/ReviewCommentControllerTest.java
  src/test/java/org/team14/webty/reviewComment/ReviewCommentControllerTest.java
Labels: new-feature

#54 fix: user 닉네임 관련 수정 & feat exceptionhandler
  src/main/java/org/team14/webty/common/exception/ErrorDetails.java
  src/main/java/org/team14/webty/common/exception/GlobalExceptionHandler.java
  src/main/java/org/team14/webty/user/repository/UserRepository.java
  src/main/java/org/team14/webty/user/service/UserService.java
Labels: hotfix

#57 feat: Webtoon 단일 조회 (id)
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/webtoon/controller/WebtoonController.java
  src/main/java/org/team14/webty/webtoon/dto/WebtoonDetailDto.java
  src/main/java/org/team14/webty/webtoon/mapper/WebtoonDetailMapper.java
  src/main/java/org/team14/webty/webtoon/service/WebtoonService.java
Labels: new-feature

#64 typo-fix: 재귀적 하위댓글 조회기능 오류를 네이티브 쿼리로 변경
  src/main/java/org/team14/webty/reviewComment/repository/ReviewCommentRepository.java
Labels: typo-fix

#65 feat: 웹툰 검색기능 추가
  src/main/java/org/team14/webty/common/dto/PageDto.java
  src/main/java/org/team14/webty/common/mapper/PageMapper.java
  src/main/java/org/team14/webty/security/authentication/CustomAuthenticationFilter.java
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/webtoon/controller/WebtoonController.java
  src/main/java/org/team14/webty/webtoon/dto/WebtoonSearchRequest.java
  src/main/java/org/team14/webty/webtoon/enumerate/WebtoonSort.java
  src/main/java/org/team14/webty/webtoon/repository/WebtoonRepository.java
  src/main/java/org/team14/webty/webtoon/service/WebtoonService.java
Labels: new-feature

#70 tests-passed: 테스트케이스 재작성 및 보완, 확인완료
  src/main/java/org/team14/webty/reviewComment/entity/ReviewComment.java
  src/test/java/org/team14/webty/reviewComment/ReviewCommentControllerTest.java
Labels: tests-passed

#73 fix: FileStorageUtil & Security CORS
  src/main/java/org/team14/webty/common/util/FileStorageUtil.java
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/user/service/UserService.java
  src/main/resources/docs/application.md
Labels: rebuild, critical-bug

#74 refactor: UserDetails Principal, AuthWebtyUserProvider Implement
  src/main/java/org/team14/webty/security/authentication/AuthWebtyUserProvider.java
  src/main/java/org/team14/webty/security/authentication/WebtyUserDetailsService.java
  src/main/java/org/team14/webty/security/oauth2/LoginSuccessHandler.java
  src/main/java/org/team14/webty/security/token/JwtManager.java
  src/main/java/org/team14/webty/user/controller/UserController.java
  src/main/java/org/team14/webty/user/dto/UserDataResponse.java
  src/main/java/org/team14/webty/user/entity/WebtyUser.java
  src/main/java/org/team14/webty/user/repository/UserRepository.java
  src/main/java/org/team14/webty/user/service/UserService.java
  src/main/java/org/team14/webty/webtoon/controller/FavoriteController.java
  src/main/java/org/team14/webty/webtoon/service/FavoriteService.java
Labels: multiple-file-changes, execution-ok

#78 refactor: 기본 닉네임 수정
  src/main/java/org/team14/webty/user/service/UserService.java
Labels: refactor

#82 chore: url 수정
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/user/entity/WebtyUser.java
  src/main/java/org/team14/webty/webtoon/controller/WebtoonController.java
Labels: no-impact, frontend-sync

#84 Fix: Controller url 수정
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/webtoon/controller/FavoriteController.java
  src/main/java/org/team14/webty/webtoon/controller/WebtoonController.java
  src/main/java/org/team14/webty/webtoon/entity/Favorite.java
  src/main/java/org/team14/webty/webtoon/service/FavoriteService.java
Labels: frontend-sync

#87 improvement: 멘토링 결과 반영
  src/main/java/org/team14/webty/reviewComment/dto/CommentResponse.java
  src/main/java/org/team14/webty/reviewComment/entity/ReviewComment.java
  src/main/java/org/team14/webty/reviewComment/repository/ReviewCommentRepository.java
  src/main/java/org/team14/webty/reviewComment/service/ReviewCommentService.java
  src/test/java/org/team14/webty/reviewComment/ReviewCommentControllerTest.java
Labels: improvement

#95 Refactor: Review , ReviewComment
  build.gradle
  src/main/java/org/team14/webty/common/exception/ErrorCode.java
  src/main/java/org/team14/webty/review/controller/ReviewController.java
  src/main/java/org/team14/webty/review/dto/FeedReviewDetailResponse.java
  src/main/java/org/team14/webty/review/dto/FeedReviewPageResponse.java
  src/main/java/org/team14/webty/review/dto/FeedReviewResponse.java
  src/main/java/org/team14/webty/review/dto/ReviewRequest.java
  src/main/java/org/team14/webty/review/dto/SearchReviewPageResponse.java
  src/main/java/org/team14/webty/review/entity/Review.java
  src/main/java/org/team14/webty/review/enumrate/SpoilerStatus.java
  src/main/java/org/team14/webty/review/mapper/ReviewMapper.java
  src/main/java/org/team14/webty/review/repository/ReviewRepository.java
  src/main/java/org/team14/webty/review/service/ReviewService.java
  src/main/java/org/team14/webty/reviewComment/mapper/ReviewCommentMapper.java
  src/main/java/org/team14/webty/reviewComment/repository/ReviewCommentRepository.java
  src/main/java/org/team14/webty/reviewComment/service/ReviewCommentService.java
  src/main/java/org/team14/webty/security/authentication/CustomAuthenticationFilter.java
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/webtoon/controller/WebtoonController.java
Labels: refactor

#94 chore: application.md 수정사항
  src/main/java/org/team14/webty/user/dto/UserDataResponse.java
  src/main/resources/docs/application.md
Labels: bugfix

#86 feat: Add Swagger
  README.md
  src/main/java/org/team14/webty/common/config/SwaggerConfig.java
  src/main/java/org/team14/webty/common/cookies/CookieManager.java
  src/main/java/org/team14/webty/common/exception/GlobalExceptionHandler.java
  src/main/java/org/team14/webty/security/authentication/CustomAuthenticationFilter.java
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/user/controller/UserController.java
  src/main/resources/docs/application.md
  src/test/java/org/team14/webty/WebtyApplicationTests.java
  src/test/java/org/team14/webty/reviewComment/ReviewCommentControllerTest.java
Labels: multiple-file-changes, rebuild, docs-update

#101 refactor fileStorage function
  src/main/java/org/team14/webty/common/exception/ErrorCode.java
  src/main/java/org/team14/webty/common/util/FileStorageUtil.java
  src/main/java/org/team14/webty/user/service/UserService.java
Labels: refactor

#105 Feat:리뷰 작성시 이미지 추가, Fix: 관심웹툰 DTO 수정
  src/main/java/org/team14/webty/WebtyApplication.java
  src/main/java/org/team14/webty/common/exception/ErrorCode.java
  src/main/java/org/team14/webty/common/util/FileStorageUtil.java
  src/main/java/org/team14/webty/review/controller/ReviewController.java
  src/main/java/org/team14/webty/review/dto/FeedReviewDetailResponse.java
  src/main/java/org/team14/webty/review/dto/FeedReviewResponse.java
  src/main/java/org/team14/webty/review/dto/ReviewRequest.java
  src/main/java/org/team14/webty/review/entity/ReviewImage.java
  src/main/java/org/team14/webty/review/mapper/ReviewMapper.java
  src/main/java/org/team14/webty/review/repository/ReviewImageRepository.java
  src/main/java/org/team14/webty/review/repository/ReviewRepository.java
  src/main/java/org/team14/webty/review/service/ReviewService.java
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/webtoon/controller/FavoriteController.java
  src/main/java/org/team14/webty/webtoon/dto/WebtoonResponseDto.java
  src/main/java/org/team14/webty/webtoon/mapper/WebtoonApiResponseMapper.java
  src/main/java/org/team14/webty/webtoon/service/FavoriteService.java
Labels: bugfix, new-feature

#110 Fix: ReviewService 수정
  src/main/java/org/team14/webty/review/service/ReviewService.java
Labels: bugfix

#109 feat: 리뷰 검색 기능 추가
  src/main/java/org/team14/webty/review/controller/ReviewController.java
  src/main/java/org/team14/webty/review/repository/ReviewRepository.java
  src/main/java/org/team14/webty/review/service/ReviewService.java
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
Labels: new-feature

#112 chore: FeedReviewResponse edit
  src/main/java/org/team14/webty/review/dto/FeedReviewResponse.java
  src/main/java/org/team14/webty/review/entity/Review.java
  src/main/java/org/team14/webty/review/mapper/ReviewMapper.java
Labels: shared-feature

#116 feat: 추천[Recommend] 기능 구현
  src/main/java/org/team14/webty/common/exception/ErrorCode.java
  src/main/java/org/team14/webty/recommend/controller/RecommendController.java
  src/main/java/org/team14/webty/recommend/entity/Recommend.java
  src/main/java/org/team14/webty/recommend/enumerate/LikeType.java
  src/main/java/org/team14/webty/recommend/repository/RecommendRepository.java
  src/main/java/org/team14/webty/recommend/service/RecommendService.java
Labels: new-feature

#120 refact: 필수 수정사항 반영(StandardResponse제거)
  src/main/java/org/team14/webty/reviewComment/controller/ReviewCommentController.java
  src/main/java/org/team14/webty/reviewComment/dto/CommentRequest.java
  src/main/java/org/team14/webty/reviewComment/dto/CommentResponse.java
  src/main/java/org/team14/webty/reviewComment/dto/StandardResponse.java
  src/main/java/org/team14/webty/reviewComment/entity/ReviewComment.java
  src/main/java/org/team14/webty/reviewComment/mapper/ReviewCommentMapper.java
  src/main/java/org/team14/webty/reviewComment/service/ReviewCommentService.java
  src/test/java/org/team14/webty/reviewComment/ReviewCommentControllerTest.java
Labels: refactor

#126 feat: 추천수 관련 기능 추가
  src/main/java/org/team14/webty/recommend/repository/RecommendRepository.java
  src/main/java/org/team14/webty/review/dto/ReviewDetailResponse.java
  src/main/java/org/team14/webty/review/dto/ReviewItemResponse.java
  src/main/java/org/team14/webty/review/mapper/ReviewMapper.java
  src/main/java/org/team14/webty/review/service/ReviewService.java
Labels: frontend-sync

#129 fix 조회수 추천수
  src/main/java/org/team14/webty/recommend/repository/RecommendRepository.java
  src/main/java/org/team14/webty/review/service/ReviewService.java
Labels: critical-bug

#131 feat: 특정 리뷰 특정 사용자 추천현황 조회
  src/main/java/org/team14/webty/recommend/controller/RecommendController.java
  src/main/java/org/team14/webty/recommend/repository/RecommendRepository.java
  src/main/java/org/team14/webty/recommend/service/RecommendService.java
Labels: new-feature

#133 refactor: ReviewDetailResponse 수정
  src/main/java/org/team14/webty/review/dto/ReviewDetailResponse.java
  src/main/java/org/team14/webty/review/mapper/ReviewMapper.java
Labels: refactor

#137 [Vote] Feat: 유사 웹툰, 투표 기능
  src/main/java/org/team14/webty/common/exception/ErrorCode.java
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/voting/controller/SimilarController.java
  src/main/java/org/team14/webty/voting/controller/VoteController.java
  src/main/java/org/team14/webty/voting/dto/SimilarRequest.java
  src/main/java/org/team14/webty/voting/dto/SimilarResponse.java
  src/main/java/org/team14/webty/voting/dto/SimilarResponseRequest.java
  src/main/java/org/team14/webty/voting/dto/VoteRequest.java
  src/main/java/org/team14/webty/voting/entity/Similar.java
  src/main/java/org/team14/webty/voting/entity/Vote.java
  src/main/java/org/team14/webty/voting/enumerate/VoteType.java
  src/main/java/org/team14/webty/voting/mapper/SimilarMapper.java
  src/main/java/org/team14/webty/voting/mapper/VoteMapper.java
  src/main/java/org/team14/webty/voting/repository/SimilarRepository.java
  src/main/java/org/team14/webty/voting/repository/VoteRepository.java
  src/main/java/org/team14/webty/voting/service/SimilarService.java
  src/main/java/org/team14/webty/voting/service/VoteService.java
  src/main/java/org/team14/webty/webtoon/repository/WebtoonRepository.java
Labels: new-feature

#138 chore: ReviewController /reviews/me
  src/main/java/org/team14/webty/review/controller/ReviewController.java
  src/main/java/org/team14/webty/review/repository/ReviewRepository.java
  src/main/java/org/team14/webty/review/service/ReviewService.java
Labels: no-impact

#140 feat WebtoonId 기반 Review 조회
  src/main/java/org/team14/webty/review/controller/ReviewController.java
  src/main/java/org/team14/webty/review/repository/ReviewRepository.java
  src/main/java/org/team14/webty/review/service/ReviewService.java
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
Labels: new-feature, backend-sync

#142 refactor: ReviewDetailResponse, ReviewItemResponse 수정
  src/main/java/org/team14/webty/review/dto/ReviewDetailResponse.java
  src/main/java/org/team14/webty/review/dto/ReviewItemResponse.java
  src/main/java/org/team14/webty/review/mapper/ReviewMapper.java
  src/main/java/org/team14/webty/reviewComment/controller/ReviewCommentController.java
  src/main/java/org/team14/webty/webtoon/dto/WebtoonSummaryDto.java
  src/main/java/org/team14/webty/webtoon/mapper/WebtoonApiResponseMapper.java
Labels: frontend-sync

#144 feat 리뷰 스포일러 처리 컨트롤러
  src/main/java/org/team14/webty/review/controller/ReviewController.java
  src/main/java/org/team14/webty/review/entity/Review.java
  src/main/java/org/team14/webty/review/service/ReviewService.java
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
Labels: new-feature

#148 feature: 댓글 대댓글관련 최종보완
  src/main/java/org/team14/webty/reviewComment/controller/ReviewCommentController.java
  src/main/java/org/team14/webty/reviewComment/dto/CommentResponse.java
  src/main/java/org/team14/webty/reviewComment/mapper/ReviewCommentMapper.java
Labels: execution-ok

#150 test: RecommendController 테스트 코드 작성
  build.gradle
  src/main/java/org/team14/webty/common/dto/PageDto.java
  src/main/java/org/team14/webty/recommend/repository/RecommendRepository.java
  src/main/java/org/team14/webty/recommend/service/RecommendService.java
  src/test/java/org/team14/webty/recommend/RecommendControllerTest.java
  src/test/java/org/team14/webty/review/controller/RecommendControllerTest.java
Labels: tests-passed

#152 feat ReviewController 테스트코드 작성
  src/test/java/org/team14/webty/review/controller/ReviewControllerTest.java
Labels: tests-passed

#154 test: 웹툰 테스트코드 작성(id로 조회, 검색)
  src/test/java/org/team14/webty/webtoon/controller/WebtoonControllerTest.java
Labels: tests-passed

#157 test: Implement SimilarControllerTest createSimilar
  src/main/java/org/team14/webty/voting/controller/SimilarController.java
  src/main/java/org/team14/webty/voting/dto/SimilarRequest.java
  src/main/java/org/team14/webty/voting/dto/SimilarResponse.java
  src/main/java/org/team14/webty/voting/dto/SimilarResponseRequest.java
  src/main/java/org/team14/webty/voting/entity/Similar.java
  src/main/java/org/team14/webty/voting/mapper/SimilarMapper.java
  src/main/java/org/team14/webty/voting/repository/SimilarRepository.java
  src/main/java/org/team14/webty/voting/service/SimilarService.java
  src/test/java/org/team14/webty/voting/controller/SimilarControllerTest.java
Labels: rebuild, tests-passed, refactor, execution-ok

#163 test: SimilarControllerTest Delete, GetList
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/voting/controller/SimilarController.java
  src/test/java/org/team14/webty/voting/controller/SimilarControllerTest.java
Labels: tests-passed

#166 test: commentController 테스트코드작성& SecurityConfig comment관련URL추가
  src/main/java/org/team14/webty/reviewComment/controller/ReviewCommentController.java
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/test/java/org/team14/webty/reviewComment/controller/ReviewCommentControllerTest.java
Labels: tests-passed

#177 refactor ReviewService
  src/main/java/org/team14/webty/review/service/ReviewService.java
Labels: refactor

#179 fix: RecommendControllerTest 수정
  src/main/java/org/team14/webty/reviewComment/controller/ReviewCommentController.java
  src/test/java/org/team14/webty/WebtyApplicationTests.java
  src/test/java/org/team14/webty/recommend/controller/RecommendControllerTest.java
Labels: bugfix

#175 Fix: recommand/issue 173
  src/main/java/org/team14/webty/recommend/repository/RecommendRepository.java
  src/main/java/org/team14/webty/recommend/service/RecommendService.java
  src/main/java/org/team14/webty/review/service/ReviewService.java
  src/main/java/org/team14/webty/reviewComment/service/ReviewCommentService.java
Labels: bugfix

#189 fix: recommandService import문추가
  src/main/java/org/team14/webty/recommend/service/RecommendService.java
Labels: bugfix

#188 fix 중복코드 삭제
  src/main/java/org/team14/webty/review/service/ReviewService.java
Labels: bugfix

#185 fix JwtManagerTest
  src/test/java/org/team14/webty/security/token/JwtManagerTest.java
Labels: bugfix, tests-passed

#196 fix:SecurityConfig, ReviewComment error solved
  src/main/java/org/team14/webty/reviewComment/entity/ReviewComment.java
Labels: bugfix

#193 feat: LoginSuccessHandlerTest
  src/test/java/org/team14/webty/security/oauth2/LoginSuccessHandlerTest.java
Labels: tests-passed

#197 feat: CustomAuthenticationFilterTest
  src/test/java/org/team14/webty/security/authentication/CustomAuthenticationFilterTest.java
Labels: tests-passed

#200 feat: BaseEntity 추가
  src/main/java/org/team14/webty/common/config/JpaConfig.java
  src/main/java/org/team14/webty/common/entity/BaseEntity.java
  src/main/java/org/team14/webty/review/entity/Review.java
  src/main/java/org/team14/webty/review/mapper/ReviewMapper.java
  src/main/java/org/team14/webty/reviewComment/entity/ReviewComment.java
Labels: new-feature

#203 fix: BaseEntity 반영 후 테스트 error 수정
  src/test/java/org/team14/webty/recommend/controller/RecommendControllerTest.java
  src/test/java/org/team14/webty/review/controller/ReviewControllerTest.java
  src/test/java/org/team14/webty/reviewComment/controller/ReviewCommentControllerTest.java
  src/test/java/org/team14/webty/webtoon/controller/WebtoonControllerTest.java
Labels: bugfix
